version: '3.5'

services:
  redis:
    image: redis
    container_name: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db

  backend:
    image: backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db
    volumes:
      - ./logs.txt:/backend/logs.txt
    depends_on:
      - db
  
  frontend:
    image: frontend
    ports:
      - 5000:5000