version: '3.5'

services:
  redis:
    image: redis
    container_name: redis

  backend:
    image: backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
    volumes:
      - ./logs.txt:/backend/logs.txt
  
  frontend:
    image: frontend
    ports:
      - 5000:5000